name: gator_calisthenics_fitness_tracker
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animated_background: ^1.0.5
  intl: ^0.16.1
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0 
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.1+3
  curved_navigation_bar: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/